---
- name: Add ExecStop to tailscaled service and reload systemd
  # 이 플레이북을 실행할 호스트 그룹을 지정합니다.
  hosts: all
  
  # 시스템 파일을 수정하고 systemd를 제어해야 하므로 루트 권한이 필요합니다.
  become: yes

  tasks:
    # ----------------------------------------------------------------
    # 단계 1: Systemd 오버라이드 디렉토리 생성 (변경 없음)
    # ----------------------------------------------------------------
    - name: "Ensure the override directory for tailscaled.service exists"
      # file 모듈을 사용하여 오버라이드 설정을 담을 디렉토리를 생성합니다.
      # 이 디렉토리가 이미 존재하면 아무 작업도 하지 않습니다.
      ansible.builtin.file:
        path: "/etc/systemd/system/tailscaled.service.d"
        state: directory
        owner: root
        group: root
        mode: '0755'

    # ----------------------------------------------------------------
    # 단계 2: [추가] 오버라이드 파일이 존재하는지 확인
    # ----------------------------------------------------------------
    - name: "Check if the override file already exists"
      # stat 모듈을 사용하여 파일의 존재 여부를 확인하고 그 결과를 변수에 저장합니다.
      ansible.builtin.stat:
        path: "/etc/systemd/system/tailscaled.service.d/override.conf"
      register: override_file_status

    # ----------------------------------------------------------------
    # 단계 3: [수정] 파일이 존재할 경우에만 ExecStop 설정 추가
    # ----------------------------------------------------------------
    - name: "Ensure ExecStop is present in the override file if it exists"
      # ini_file 모듈은 INI 파일의 특정 섹션에 특정 키-값 쌍이 있는지 확인하고 관리합니다.
      community.general.ini_file:
        path: "/etc/systemd/system/tailscaled.service.d/override.conf"
        section: "Service"
        option: "ExecStop"
        value: "/usr/sbin/tailscaled -s stop"
        owner: root
        group: root
        mode: '0644'
      
      # [핵심] 바로 위 stat 작업의 결과, 파일이 존재할 때만(when) 이 작업을 실행합니다.
      when: override_file_status.stat.exists
      
      # 이 작업으로 인해 파일 내용이 변경되었을 경우에만 'handler'를 호출합니다.
      notify: Reload systemd daemon

  # ------------------------------------------------------------------
  # 핸들러(Handlers): 특정 작업에 의해 호출될 때만 실행되는 작업 (변경 없음)
  # ------------------------------------------------------------------
  handlers:
    - name: Reload systemd daemon
      # systemd 모듈을 사용하여 'systemctl daemon-reload'를 실행합니다.
      # 이 핸들러는 오버라이드 파일이 실제로 생성되거나 변경되었을 때만 단 한 번 실행됩니다.
      ansible.builtin.systemd:
        daemon_reload: yes


