---
- name: Compare host facts and generate a CSV report
  # 인벤토리에 정의된 모든 호스트를 대상으로 합니다.
  hosts: all
  
  # [수정] Facts 수집 단계를 건너뛰어 AWX에 캐시된 데이터를 사용합니다.
  gather_facts: no
  
  # 변수 정의
  vars:
    # 보고서에 포함할 CSV 헤더를 정의합니다.
    # 여기에 원하는 항목의 제목을 추가할 수 있습니다.
    csv_header: "Hostname,Distribution,Distro_Version,Memory_MB,CPU_Cores,IP_Address"

  tasks:
    # ----------------------------------------------------------------
    # 단계 1: 모든 호스트의 Facts를 취합하여 CSV 형식으로 출력
    # ----------------------------------------------------------------
    - name: "Generate and print a CSV report of host facts"
      # delegate_to: localhost -> 보고서 생성 작업은 하나의 제어 지점에서 실행됩니다.
      # run_once: true -> 이 작업은 전체 플레이북에서 딱 한 번만 실행됩니다.
      delegate_to: localhost
      run_once: true
      
      # debug 모듈을 사용하여 변수나 메시지를 표준 출력으로 보여줍니다.
      ansible.builtin.debug:
        # msg를 사용하여 여러 줄의 문자열을 만듭니다.
        msg: |
          {{ csv_header }}
          {% for host in ansible_play_hosts_all %}
          {%   set facts = hostvars[host].ansible_facts %}
          {{- host -}}
          ,{{- facts.distribution | default('N/A') -}}
          ,{{- facts.distribution_version | default('N/A') -}}
          ,{{- facts.memtotal_mb | default('N/A') -}}
          ,{{- facts.processor_vcpus | default('N/A') -}}
          ,{{- facts.default_ipv4.address | default('N/A') -}}
          {% endfor %}


