download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/flowerysong-hvault-0.3.0.tar.gz
format_version: 1.0.0
name: hvault
namespace: flowerysong
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.3.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/flowerysong/hvault/versions/0.3.0/
